# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-01-19 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('images', models.ImageField(blank=True, upload_to='category/%Y/%m/%d/', verbose_name='Изображение Категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара')),
                ('opisanie', tinymce.models.HTMLField(default=True, verbose_name='Описание')),
                ('tech', tinymce.models.HTMLField(default=True, verbose_name='Технические характеристики')),
                ('complects', tinymce.models.HTMLField(default=True, verbose_name='Комплектация')),
                ('docs', tinymce.models.HTMLField(default=True, verbose_name='Документация')),
                ('photo', tinymce.models.HTMLField(default=True, verbose_name='Фотогалерея')),
                ('video', tinymce.models.HTMLField(default=True, verbose_name='Видеообзоры')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('sku', models.CharField(default=True, max_length=200, verbose_name='Артикул')),
                ('size', models.FloatField(default=0.003, verbose_name='Размер')),
                ('mass', models.IntegerField(default=100, verbose_name='Вес')),
                ('stock', models.PositiveIntegerField(verbose_name='На складе')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('dopproduct', models.BooleanField(default=False, verbose_name='Допоборудование')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['slug'],
            },
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([('id', 'slug')]),
        ),
    ]
