# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-01-20 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images2',
            field=models.ImageField(blank=True, upload_to='category/%Y/%m/%d/', verbose_name='Изображение2 Категории'),
        ),
    ]
