# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-01-21 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_images2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vibor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='vibor/%Y/%m/%d/', verbose_name='Изображение выбора')),
                ('image2', models.ImageField(blank=True, upload_to='vibor/%Y/%m/%d/', verbose_name='Изображение2 выбора')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vibors', to='shop.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Выбор',
                'verbose_name_plural': 'Выборы',
                'ordering': ['slug'],
            },
        ),
        migrations.AlterIndexTogether(
            name='vibor',
            index_together=set([('id', 'slug')]),
        ),
    ]
