# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-01-21 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200121_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='shop.Vibor', verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='vibor',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Тег'),
        ),
    ]
