# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-01-24 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200123_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagesm',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение маленькое товара1'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagesm2',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение маленькое товара2'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagesm3',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение маленькое товара3'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagesm4',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение маленькое товара4'),
        ),
    ]
