# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-02-10 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200124_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='anons',
            field=tinymce.models.HTMLField(default=True, verbose_name='Анонс'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара5'),
        ),
        migrations.AddField(
            model_name='product',
            name='image6',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара6'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagemed',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение среднее'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagesm5',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение маленькое товара5'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagesm6',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение маленькое товара6'),
        ),
    ]
